### ISSUE TITLE
invisibility bug

### ISSUE THREAD

**Issue by pompompur1nn** [NotNite/WebfishingPlus#2]
after a few relaunches, the mod just tweaks out and everyone in the servers invisible and your name turns into null

**Comment by pompompur1nn** [comment]
update: i turned off menu tweaks and turned on netcode improvements and the bug fixed itself

**Comment by pompompur1nn** [comment]
its back nvm

**Comment by NotNite** [comment]
Can not reproduce, "null" implies that Steam authentication is offline
